initiatice_admin:
    resource: "@initiaticeAdminBundle/Resources/config/routing.yml"
    prefix:   /

initiatice_api:
    resource: "@initiaticeApiBundle/Resources/config/routing.yml"
    prefix:   /

