initiatice_admin_homepage:
    path:     /
    defaults: { _controller: initiaticeAdminBundle:Default:index }

initiatice_admin_user_index:
    path:     /user
    defaults: { _controller: initiaticeAdminBundle:User:index }

initiatice_admin_user_remove:
    path:     /user/remove/{id}
    defaults: { _controller: initiaticeAdminBundle:User:remove }
    requirements:
        id: \d+



initiatice_admin_news_index:
    path:     /news
    defaults: { _controller: initiaticeAdminBundle:News:index }

initiatice_admin_news_add:
    path:     /news/add
    defaults: { _controller: initiaticeAdminBundle:News:add }

initiatice_admin_news_edit:
    path:     /news/edit/{id}
    defaults: { _controller: initiaticeAdminBundle:News:edit }
    requirements:
            id: \d+
    
initiatice_admin_news_remove:
    path:     /news/remove/{id}
    defaults: { _controller: initiaticeAdminBundle:News:remove }
    requirements:
        id: \d+



initiatice_admin_event_index:
    path:     /event
    defaults: { _controller: initiaticeAdminBundle:Event:index }

initiatice_admin_event_add:
    path:     /event/add
    defaults: { _controller: initiaticeAdminBundle:Event:add }

initiatice_admin_event_edit:
    path:     /event/edit/{id}
    defaults: { _controller: initiaticeAdminBundle:Event:edit }
    requirements:
            id: \d+

initiatice_admin_event_remove:
    path:     /event/remove/{id}
    defaults: { _controller: initiaticeAdminBundle:Event:remove }
    requirements:
        id: \d+



initiatice_admin_forum_question_index:
    path:     /forum/question
    defaults: { _controller: initiaticeAdminBundle:ForumQuestion:index }

initiatice_admin_forum_question_add:
    path:     /forum/question/add
    defaults: { _controller: initiaticeAdminBundle:ForumQuestion:add }

initiatice_admin_forum_question_edit:
    path:     /forum/question/edit/{id}
    defaults: { _controller: initiaticeAdminBundle:ForumQuestion:edit }
    requirements:
            id: \d+

initiatice_admin_forum_question_remove:
    path:     /forum/question/remove/{id}
    defaults: { _controller: initiaticeAdminBundle:ForumQuestion:remove }
    requirements:
        id: \d+



initiatice_admin_forum_comment_index:
    path:     /forum/comment
    defaults: { _controller: initiaticeAdminBundle:ForumComment:index }

initiatice_admin_forum_comment_add:
    path:     /forum/comment/add
    defaults: { _controller: initiaticeAdminBundle:ForumComment:add }

initiatice_admin_forum_comment_edit:
    path:     /forum/comment/edit/{id}
    defaults: { _controller: initiaticeAdminBundle:ForumComment:edit }
    requirements:
            id: \d+

initiatice_admin_forum_comment_remove:
    path:     /forum/comment/remove/{id}
    defaults: { _controller: initiaticeAdminBundle:ForumComment:remove }
    requirements:
        id: \d+